/// Flutter icons AppIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class StepIcons {
  StepIcons._();

  static const _kFontFam = 'AppIcons';

  static const IconData cooler = IconData(0xe800, fontFamily: _kFontFam, fontPackage: null);
  static const IconData power_plug = IconData(0xe801, fontFamily: _kFontFam, fontPackage: null);
  static const IconData power_button = IconData(0xe802, fontFamily: _kFontFam, fontPackage: null);
  static const IconData processor = IconData(0xe803, fontFamily: _kFontFam, fontPackage: null);
  static const IconData power_supply = IconData(0xe804, fontFamily: _kFontFam, fontPackage: null);
  static const IconData gpu = IconData(0xe805, fontFamily: _kFontFam, fontPackage: null);
  static const IconData ram = IconData(0xe806, fontFamily: _kFontFam, fontPackage: null);
  static const IconData motherboard = IconData(0xe807, fontFamily: _kFontFam, fontPackage: null);
  static const IconData question_mark = IconData(0xe809, fontFamily: _kFontFam, fontPackage: null);
  static const IconData slave_hard_drive = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: null);
}
