/// Flutter icons PCPartInfoIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PCPartInfoIcons
///      fonts:
///       - asset: fonts/PCPartInfoIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PCPartInfoIcons {
  PCPartInfoIcons._();

  static const _kFontFam = 'PCPartInfoIcons';
  static const String _kFontPkg = null;

  static const IconData dollar = IconData(0xe800, fontFamily: _kFontFam, fontPackage: null);
  static const IconData manufacturer = IconData(0xe801, fontFamily: _kFontFam, fontPackage: null);
  static const IconData hashtag = IconData(0xe802, fontFamily: _kFontFam, fontPackage: null);
  static const IconData base_clock = IconData(0xe803, fontFamily: _kFontFam, fontPackage: null);
  static const IconData boost_clock = IconData(0xe804, fontFamily: _kFontFam, fontPackage: null);
}
